// Liste de lieux generee depuis l'API UEX Corp (https://uexcorp.space/api/documentation/).
// Un lieu par station/ville/avant-poste/lune (dedoublonne), avec l'ID de terminal UEX
// (uexTerminalId) et l'ID d'orbite (orbitId) associes, utilises pour les distances.
// Genere le 2026-07-13. Utilise le bouton de synchronisation dans l'app pour rafraichir.
const DEFAULT_LOCATIONS = [
  { id: "uex-outpost-1", name: "ArcCorp Mining Area 045", category: "Avant-poste", uexTerminalId: 6, orbitId: 4 },
  { id: "uex-outpost-2", name: "ArcCorp Mining Area 048", category: "Avant-poste", uexTerminalId: 7, orbitId: 4 },
  { id: "uex-outpost-3", name: "ArcCorp Mining Area 056", category: "Avant-poste", uexTerminalId: 8, orbitId: 4 },
  { id: "uex-outpost-4", name: "ArcCorp Mining Area 061", category: "Avant-poste", uexTerminalId: 9, orbitId: 4 },
  { id: "uex-outpost-5", name: "ArcCorp Mining Area 141", category: "Avant-poste", uexTerminalId: 10, orbitId: 59 },
  { id: "uex-outpost-6", name: "ArcCorp Mining Area 157", category: "Avant-poste", uexTerminalId: 11, orbitId: 59 },
  { id: "uex-outpost-60", name: "Astor's Clearing", category: "Avant-poste", uexTerminalId: 264, orbitId: 190 },
  { id: "uex-outpost-9", name: "Brio's Breaker Yard", category: "Avant-poste", uexTerminalId: 16, orbitId: 59 },
  { id: "uex-outpost-11", name: "Deakins Research", category: "Avant-poste", uexTerminalId: 23, orbitId: 59 },
  { id: "uex-outpost-12", name: "Devlin Scrap & Salvage", category: "Avant-poste", uexTerminalId: 24, orbitId: 190 },
  { id: "uex-outpost-62", name: "Dunboro", category: "Avant-poste", uexTerminalId: 266, orbitId: 190 },
  { id: "uex-outpost-83", name: "Frostbite", category: "Avant-poste", uexTerminalId: 351, orbitId: 190 },
  { id: "uex-outpost-14", name: "HDMS-Anderson", category: "Avant-poste", uexTerminalId: 28, orbitId: 116 },
  { id: "uex-outpost-15", name: "HDMS-Bezdek", category: "Avant-poste", uexTerminalId: 29, orbitId: 116 },
  { id: "uex-outpost-16", name: "HDMS-Edmond", category: "Avant-poste", uexTerminalId: 30, orbitId: 116 },
  { id: "uex-outpost-17", name: "HDMS-Hadley", category: "Avant-poste", uexTerminalId: 31, orbitId: 116 },
  { id: "uex-outpost-18", name: "HDMS-Hahn", category: "Avant-poste", uexTerminalId: 32, orbitId: 116 },
  { id: "uex-outpost-19", name: "HDMS-Lathan", category: "Avant-poste", uexTerminalId: 33, orbitId: 116 },
  { id: "uex-outpost-20", name: "HDMS-Norgaard", category: "Avant-poste", uexTerminalId: 34, orbitId: 116 },
  { id: "uex-outpost-21", name: "HDMS-Oparei", category: "Avant-poste", uexTerminalId: 35, orbitId: 116 },
  { id: "uex-outpost-22", name: "HDMS-Perlman", category: "Avant-poste", uexTerminalId: 36, orbitId: 116 },
  { id: "uex-outpost-23", name: "HDMS-Pinewood", category: "Avant-poste", uexTerminalId: 37, orbitId: 116 },
  { id: "uex-outpost-24", name: "HDMS-Ryder", category: "Avant-poste", uexTerminalId: 38, orbitId: 116 },
  { id: "uex-outpost-25", name: "HDMS-Stanhope", category: "Avant-poste", uexTerminalId: 39, orbitId: 116 },
  { id: "uex-outpost-26", name: "HDMS-Thedus", category: "Avant-poste", uexTerminalId: 40, orbitId: 116 },
  { id: "uex-outpost-27", name: "HDMS-Woodruff", category: "Avant-poste", uexTerminalId: 41, orbitId: 116 },
  { id: "uex-outpost-28", name: "Hickes Research", category: "Avant-poste", uexTerminalId: 42, orbitId: 59 },
  { id: "uex-outpost-66", name: "Picker's Field", category: "Avant-poste", uexTerminalId: 276, orbitId: 116 },
  { id: "uex-outpost-65", name: "Rappel", category: "Avant-poste", uexTerminalId: 274, orbitId: 116 },
  { id: "uex-outpost-39", name: "Rayari Anvik Research Outpost", category: "Avant-poste", uexTerminalId: 69, orbitId: 190 },
  { id: "uex-outpost-40", name: "Rayari Cantwell Research Outpost", category: "Avant-poste", uexTerminalId: 70, orbitId: 190 },
  { id: "uex-outpost-41", name: "Rayari Deltana Research Outpost", category: "Avant-poste", uexTerminalId: 71, orbitId: 190 },
  { id: "uex-outpost-42", name: "Rayari Kaltag Research Outpost", category: "Avant-poste", uexTerminalId: 72, orbitId: 190 },
  { id: "uex-outpost-43", name: "Rayari McGrath Research Outpost", category: "Avant-poste", uexTerminalId: 73, orbitId: 190 },
  { id: "uex-outpost-44", name: "Reclamation & Disposal Orinth", category: "Avant-poste", uexTerminalId: 74, orbitId: 116 },
  { id: "uex-outpost-45", name: "Samson & Son's Salvage Center", category: "Avant-poste", uexTerminalId: 75, orbitId: 4 },
  { id: "uex-outpost-46", name: "Shubin Mining Facility SAL-2", category: "Avant-poste", uexTerminalId: 77, orbitId: 4 },
  { id: "uex-outpost-47", name: "Shubin Mining Facility SAL-5", category: "Avant-poste", uexTerminalId: 78, orbitId: 4 },
  { id: "uex-outpost-48", name: "Shubin Mining Facility SCD-1", category: "Avant-poste", uexTerminalId: 79, orbitId: 59 },
  { id: "uex-outpost-49", name: "Shubin Mining Facility SM0-10", category: "Avant-poste", uexTerminalId: 80, orbitId: 190 },
  { id: "uex-outpost-50", name: "Shubin Mining Facility SM0-13", category: "Avant-poste", uexTerminalId: 81, orbitId: 190 },
  { id: "uex-outpost-51", name: "Shubin Mining Facility SM0-18", category: "Avant-poste", uexTerminalId: 82, orbitId: 190 },
  { id: "uex-outpost-52", name: "Shubin Mining Facility SM0-22", category: "Avant-poste", uexTerminalId: 83, orbitId: 190 },
  { id: "uex-outpost-53", name: "Shubin Mining Facility SMCa-6", category: "Avant-poste", uexTerminalId: 84, orbitId: 190 },
  { id: "uex-outpost-54", name: "Shubin Mining Facility SMCa-8", category: "Avant-poste", uexTerminalId: 85, orbitId: 190 },
  { id: "uex-outpost-55", name: "Terra Mills HydroFarm", category: "Avant-poste", uexTerminalId: 86, orbitId: 59 },
  { id: "uex-outpost-78", name: "Zephyr", category: "Avant-poste", uexTerminalId: 336, orbitId: 116 },
  { id: "uex-outpost-90", name: "Arid Reach", category: "Avant-poste - Pyro", uexTerminalId: 686, orbitId: 241 },
  { id: "uex-outpost-98", name: "Ashland", category: "Avant-poste - Pyro", uexTerminalId: 507, orbitId: 244 },
  { id: "uex-outpost-104", name: "Blackrock Exchange", category: "Avant-poste - Pyro", uexTerminalId: 476, orbitId: 245 },
  { id: "uex-outpost-73", name: "Bueno Ravine", category: "Avant-poste - Pyro", uexTerminalId: 550, orbitId: 242 },
  { id: "uex-outpost-105", name: "Bullock's Reach", category: "Avant-poste - Pyro", uexTerminalId: 820, orbitId: 245 },
  { id: "uex-outpost-106", name: "Canard View", category: "Avant-poste - Pyro", uexTerminalId: 475, orbitId: 245 },
  { id: "uex-outpost-93", name: "Carver's Ridge", category: "Avant-poste - Pyro", uexTerminalId: 679, orbitId: 242 },
  { id: "uex-outpost-99", name: "Chawla's Beach", category: "Avant-poste - Pyro", uexTerminalId: 509, orbitId: 244 },
  { id: "uex-outpost-100", name: "Fallow Field", category: "Avant-poste - Pyro", uexTerminalId: 605, orbitId: 244 },
  { id: "uex-outpost-94", name: "Frigid Knot", category: "Avant-poste - Pyro", uexTerminalId: 558, orbitId: 242 },
  { id: "uex-outpost-101", name: "Goner's Deal", category: "Avant-poste - Pyro", uexTerminalId: 585, orbitId: 244 },
  { id: "uex-outpost-69", name: "Jackson's Swap", category: "Avant-poste - Pyro", uexTerminalId: 504, orbitId: 241 },
  { id: "uex-outpost-103", name: "Kabir's Post", category: "Avant-poste - Pyro", uexTerminalId: 552, orbitId: 244 },
  { id: "uex-outpost-107", name: "Kinder Plots", category: "Avant-poste - Pyro", uexTerminalId: 821, orbitId: 245 },
  { id: "uex-outpost-108", name: "Last Landings", category: "Avant-poste - Pyro", uexTerminalId: 565, orbitId: 245 },
  { id: "uex-outpost-95", name: "Narena's Rest", category: "Avant-poste - Pyro", uexTerminalId: 505, orbitId: 242 },
  { id: "uex-outpost-92", name: "Ostler's Claim", category: "Avant-poste - Pyro", uexTerminalId: 538, orbitId: 241 },
  { id: "uex-outpost-112", name: "Prophet's Peak", category: "Avant-poste - Pyro", uexTerminalId: 516, orbitId: 244 },
  { id: "uex-outpost-109", name: "Rough Landing", category: "Avant-poste - Pyro", uexTerminalId: 497, orbitId: 245 },
  { id: "uex-outpost-68", name: "Rustville", category: "Avant-poste - Pyro", uexTerminalId: 533, orbitId: 240 },
  { id: "uex-outpost-102", name: "Sacren's Plot", category: "Avant-poste - Pyro", uexTerminalId: 688, orbitId: 244 },
  { id: "uex-outpost-110", name: "Scarper's Turn", category: "Avant-poste - Pyro", uexTerminalId: 477, orbitId: 245 },
  { id: "uex-outpost-113", name: "Seer's Canyon", category: "Avant-poste - Pyro", uexTerminalId: 517, orbitId: 244 },
  { id: "uex-outpost-75", name: "Shepherd's Rest", category: "Avant-poste - Pyro", uexTerminalId: 555, orbitId: 242 },
  { id: "uex-outpost-89", name: "Stag's Rut", category: "Avant-poste - Pyro", uexTerminalId: 692, orbitId: 240 },
  { id: "uex-outpost-71", name: "Sunset Mesa", category: "Avant-poste - Pyro", uexTerminalId: 541, orbitId: 241 },
  { id: "uex-outpost-76", name: "The Golden Riviera", category: "Avant-poste - Pyro", uexTerminalId: 665, orbitId: 242 },
  { id: "uex-outpost-77", name: "The Yard", category: "Avant-poste - Pyro", uexTerminalId: 474, orbitId: 242 },
  { id: "uex-outpost-96", name: "Windfall", category: "Avant-poste - Pyro", uexTerminalId: 557, orbitId: 242 },
  { id: "uex-outpost-72", name: "Yang's Place", category: "Avant-poste - Pyro", uexTerminalId: 503, orbitId: 241 },
  { id: "uex-terminal-725", name: "Covalex Distribution Centre S4DC05", category: "Planète", uexTerminalId: 725, orbitId: 0 },
  { id: "uex-planet-190", name: "MicroTech", category: "Planète", uexTerminalId: 726, orbitId: 190 },
  { id: "uex-terminal-792", name: "NovaworX Industries", category: "Planète", uexTerminalId: 792, orbitId: 0 },
  { id: "uex-terminal-422", name: "UEX Station", category: "Planète", uexTerminalId: 422, orbitId: 0 },
  { id: "uex-station-1", name: "ARC-L1 Wide Forest Station", category: "Station", uexTerminalId: 1, orbitId: 326 },
  { id: "uex-station-2", name: "ARC-L2 Lively Pathway Station", category: "Station", uexTerminalId: 2, orbitId: 327 },
  { id: "uex-station-3", name: "ARC-L3 Modern Express Station", category: "Station", uexTerminalId: 3, orbitId: 328 },
  { id: "uex-station-4", name: "ARC-L4 Faint Glen Station", category: "Station", uexTerminalId: 4, orbitId: 329 },
  { id: "uex-station-5", name: "ARC-L5 Yellow Core Station", category: "Station", uexTerminalId: 5, orbitId: 330 },
  { id: "uex-station-6", name: "Baijini Point", category: "Station", uexTerminalId: 13, orbitId: 4 },
  { id: "uex-station-7", name: "CRU-L1 Ambitious Dream Station", category: "Station", uexTerminalId: 19, orbitId: 331 },
  { id: "uex-station-8", name: "CRU-L4 Shallow Fields Station", category: "Station", uexTerminalId: 20, orbitId: 332 },
  { id: "uex-station-9", name: "CRU-L5 Beautiful Glen Station", category: "Station", uexTerminalId: 22, orbitId: 333 },
  { id: "uex-station-10", name: "Everus Harbor", category: "Station", uexTerminalId: 25, orbitId: 116 },
  { id: "uex-station-11", name: "Green Imperial Housing Exchange", category: "Station", uexTerminalId: 27, orbitId: 59 },
  { id: "uex-station-12", name: "HUR-L1 Green Glade Station", category: "Station", uexTerminalId: 44, orbitId: 334 },
  { id: "uex-station-13", name: "HUR-L2 Faithful Dream Station", category: "Station", uexTerminalId: 45, orbitId: 335 },
  { id: "uex-station-14", name: "HUR-L3 Thundering Express Station", category: "Station", uexTerminalId: 46, orbitId: 336 },
  { id: "uex-station-15", name: "HUR-L4 Melodic Fields Station", category: "Station", uexTerminalId: 47, orbitId: 337 },
  { id: "uex-station-16", name: "HUR-L5 High Course Station", category: "Station", uexTerminalId: 48, orbitId: 338 },
  { id: "uex-station-17", name: "MIC-L1 Shallow Frontier Station", category: "Station", uexTerminalId: 54, orbitId: 339 },
  { id: "uex-station-18", name: "MIC-L2 Long Forest Station", category: "Station", uexTerminalId: 55, orbitId: 340 },
  { id: "uex-station-19", name: "MIC-L3 Endless Odyssey Station", category: "Station", uexTerminalId: 56, orbitId: 341 },
  { id: "uex-station-20", name: "MIC-L4 Red Crossroads Station", category: "Station", uexTerminalId: 57, orbitId: 342 },
  { id: "uex-station-21", name: "MIC-L5 Modern Icarus Station", category: "Station", uexTerminalId: 58, orbitId: 343 },
  { id: "uex-station-25", name: "Nyx Gateway (Stanton)", category: "Station", uexTerminalId: 253, orbitId: 394 },
  { id: "uex-station-23", name: "Port Tressler", category: "Station", uexTerminalId: 66, orbitId: 190 },
  { id: "uex-station-24", name: "Pyro Gateway (Stanton)", category: "Station", uexTerminalId: 252, orbitId: 360 },
  { id: "uex-station-27", name: "Seraphim Station", category: "Station", uexTerminalId: 259, orbitId: 59 },
  { id: "uex-station-26", name: "Terra Gateway (Stanton)", category: "Station", uexTerminalId: 251, orbitId: 361 },
  { id: "uex-station-52", name: "Wikelo Emporium Dasi Station", category: "Station", uexTerminalId: 709, orbitId: 0 },
  { id: "uex-station-51", name: "Wikelo Emporium Kinga Station", category: "Station", uexTerminalId: 710, orbitId: 0 },
  { id: "uex-station-53", name: "Wikelo Emporium Selo Station", category: "Station", uexTerminalId: 711, orbitId: 0 },
  { id: "uex-station-59", name: "People's Service Station Alpha", category: "Station - Nyx", uexTerminalId: 830, orbitId: 401 },
  { id: "uex-station-58", name: "People's Service Station Delta", category: "Station - Nyx", uexTerminalId: 834, orbitId: 402 },
  { id: "uex-station-61", name: "People's Service Station Lambda", category: "Station - Nyx", uexTerminalId: 841, orbitId: 403 },
  { id: "uex-station-60", name: "People's Service Station Theta", category: "Station - Nyx", uexTerminalId: 836, orbitId: 404 },
  { id: "uex-station-57", name: "Pyro Gateway (Nyx)", category: "Station - Nyx", uexTerminalId: 758, orbitId: 396 },
  { id: "uex-station-56", name: "Stanton Gateway (Nyx)", category: "Station - Nyx", uexTerminalId: 798, orbitId: 397 },
  { id: "uex-station-31", name: "Checkmate Station", category: "Station - Pyro", uexTerminalId: 428, orbitId: 392 },
  { id: "uex-station-42", name: "Dudley & Daughters", category: "Station - Pyro", uexTerminalId: 546, orbitId: 391 },
  { id: "uex-station-41", name: "Endgame", category: "Station - Pyro", uexTerminalId: 482, orbitId: 355 },
  { id: "uex-station-46", name: "Gaslight", category: "Station - Pyro", uexTerminalId: 511, orbitId: 388 },
  { id: "uex-station-43", name: "Megumi Refueling", category: "Station - Pyro", uexTerminalId: 478, orbitId: 374 },
  { id: "uex-station-55", name: "Nyx Gateway (Pyro)", category: "Station - Pyro", uexTerminalId: 738, orbitId: 395 },
  { id: "uex-station-32", name: "Orbituary", category: "Station - Pyro", uexTerminalId: 432, orbitId: 242 },
  { id: "uex-station-34", name: "Patch City", category: "Station - Pyro", uexTerminalId: 430, orbitId: 387 },
  { id: "uex-station-39", name: "Rat's Nest", category: "Station - Pyro", uexTerminalId: 523, orbitId: 390 },
  { id: "uex-station-38", name: "Rod's Fuel 'N Supplies", category: "Station - Pyro", uexTerminalId: 486, orbitId: 389 },
  { id: "uex-station-45", name: "Ruin Station", category: "Station - Pyro", uexTerminalId: 457, orbitId: 245 },
  { id: "uex-station-50", name: "Stanton Gateway (Pyro)", category: "Station - Pyro", uexTerminalId: 520, orbitId: 398 },
  { id: "uex-station-33", name: "Starlight Service Station", category: "Station - Pyro", uexTerminalId: 434, orbitId: 393 },
  { id: "uex-city-1", name: "Area 18", category: "Ville", uexTerminalId: 12, orbitId: 4 },
  { id: "uex-city-3", name: "Lorville", category: "Ville", uexTerminalId: 18, orbitId: 116 },
  { id: "uex-city-4", name: "New Babbage", category: "Ville", uexTerminalId: 59, orbitId: 190 },
  { id: "uex-city-5", name: "Orison", category: "Ville", uexTerminalId: 62, orbitId: 59 },
  { id: "uex-city-2", name: "Levski", category: "Ville - Nyx", uexTerminalId: 109, orbitId: 325 },
];
